In [1]:
import pandas as pd #数据分析
import numpy as np #科学计算
import visuals as vs # Supplementary code

%matplotlib inline


data_train = pd.read_csv("1.csv")
data_test = pd.read_csv("2.csv")
data_train.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NoAlley,Reg,Lvl,AllPub,...,0,NoPool,NoFence,NoMisc,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NoAlley,Reg,Lvl,AllPub,...,0,NoPool,NoFence,NoMisc,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NoAlley,IR1,Lvl,AllPub,...,0,NoPool,NoFence,NoMisc,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NoAlley,IR1,Lvl,AllPub,...,0,NoPool,NoFence,NoMisc,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NoAlley,IR1,Lvl,AllPub,...,0,NoPool,NoFence,NoMisc,0,12,2008,WD,Normal,250000

In [2]:
data_test.shape

(1459, 80)

In [3]:
#粗鲁的撸出了402列
df = pd.get_dummies(data_train)
df2 = pd.get_dummies(data_test)
df.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [4]:
df1 = pd.DataFrame(index=np.arange(0, 1),columns=df.columns)

for x in np.arange(0, 1):
    #loc or iloc both work here since the index is natural numbers
    df1.loc[x] = [9999 for n in range(402)]

df1

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999,...,9999,9999,9999,9999,9999,9999,9999,9999,9999,9999

In [5]:


df3 = df1.append(df2,ignore_index=True)

In [6]:
aa1 = df3.isnull()
aa2 = aa1.apply(lambda x: x.sum(), axis=0)
aa2[aa2 == 1]

GarageYrBlt_1895.0    1
GarageYrBlt_1896.0    1
GarageYrBlt_1917.0    1
GarageYrBlt_1919.0    1
GarageYrBlt_1943.0    1
GarageYrBlt_2207.0    1
dtype: int64

In [7]:
df4 = df3.copy()
df4 = df4.drop(['GarageYrBlt_1895.0','GarageYrBlt_1896.0','GarageYrBlt_1917.0','GarageYrBlt_1919.0','GarageYrBlt_1943.0','GarageYrBlt_2207.0','SalePrice'],axis=1)
df4 = df4.drop([0],axis=0)
df4 = df4.fillna(0)
df4.head()

,1stFlrSF,2ndFlrSF,3SsnPorch,Alley_Grvl,Alley_NoAlley,Alley_Pave,BedroomAbvGr,BldgType_1Fam,BldgType_2fmCon,BldgType_Duplex,...,Street_Grvl,Street_Pave,TotRmsAbvGrd,TotalBsmtSF,Utilities_AllPub,Utilities_NoSeWa,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold
1,896,0,0,0.0,1.0,0.0,2,1.0,0.0,0.0,...,0.0,1.0,5,882.0,1.0,0.0,140,1961,1961,2010
2,1329,0,0,0.0,1.0,0.0,3,1.0,0.0,0.0,...,0.0,1.0,6,1329.0,1.0,0.0,393,1958,1958,2010
3,928,701,0,0.0,1.0,0.0,3,1.0,0.0,0.0,...,0.0,1.0,6,928.0,1.0,0.0,212,1997,1998,2010
4,926,678,0,0.0,1.0,0.0,3,1.0,0.0,0.0,...,0.0,1.0,7,926.0,1.0,0.0,360,1998,1998,2010
5,1280,0,0,0.0,1.0,0.0,2,0.0,0.0,0.0,...,0.0,1.0,5,1280.0,1.0,0.0,0,1992,1992,2010

In [8]:
prices = df['SalePrice']
features = df.drop('SalePrice', axis = 1)

from sklearn.cross_validation import train_test_split

# 分割
X_train, X_test, y_train, y_test = train_test_split(features, prices, test_size=0.2, random_state=7)

print "分割CV数据集完毕"

分割CV数据集完毕

In [9]:
# TODO: Import 'make_scorer', 'DecisionTreeRegressor', and 'GridSearchCV'

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import make_scorer
from sklearn.grid_search import GridSearchCV

def fit_model(X, y):
    """ Performs grid search over the 'max_depth' parameter for a 
        decision tree regressor trained on the input data [X, y]. """
    
    # Create cross-validation sets from the training data
    cv_sets = ShuffleSplit(X.shape[0], n_iter = 10, test_size = 0.20, random_state = 0)
    
    for train_index, test_index in cv_sets:
        xtrain, xtest = X.iloc[train_index], X.iloc[test_index]
        ytrain, ytest = y.iloc[train_index], y.iloc[test_index]

    # TODO: Create a decision tree regressor object
    regressor = GradientBoostingRegressor()
    regressor.fit(X,y)

    # TODO: Create a dictionary for the parameter 'max_depth' with a range from 1 to 10
    params = {'max_depth' : np.arange(1,11)}
    
    # TODO: Transform 'performance_metric' into a scoring function using 'make_scorer' 
    scoring_fnc = make_scorer(performance_metric)

    # TODO: Create the grid search object
    grid = GridSearchCV(regressor,param_grid=params,cv=cv_sets,scoring=scoring_fnc)
    # Fit the grid search object to the data to compute the optimal model
    grid = grid.fit(X, y)

    # Return the optimal model after fitting the data
    return grid.best_estimator_

In [10]:
# TODO: Import 'r2_score'
from sklearn.metrics import r2_score

def performance_metric(y_true, y_predict):
    """ Calculates and returns the performance score between 
        true and predicted values based on the metric chosen. """
    
    # TODO: Calculate the performance score between 'y_true' and 'y_predict'
    score = None    
    score = r2_score(y_true,y_predict)
    # Return the score
    return score



from sklearn.cross_validation import ShuffleSplit
# Fit the training data to the model using grid search
reg = fit_model(X_train, y_train)

# Produce the value for 'max_depth'
print "Parameter 'max_depth' is {} for the optimal model.".format(reg.get_params()['max_depth'])

Parameter 'max_depth' is 5 for the optimal model.

In [13]:
treeregress = GradientBoostingRegressor(max_depth=5)
treeregress.fit(X_train, y_train)
predictions = treeregress.predict(df4)
predictions

array([ 76120.3337685 ,  71418.95438384,  60618.93970119, ...,
        69267.54594212,  72465.50222382,  76625.09077433])

In [21]:

result = pd.DataFrame({'Id':df4['Id'], 'Survived':predictions.astype(np.int32)})
result.to_csv("logistic_regression_predictions.csv", index=False)
#result.describe()
performance_metric